"""add_interview_state_field

Revision ID: 000011
Revises: 000010_add_interview_notes
Create Date: 2025-09-07 21:35:14.844520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "000018"
down_revision: Union[str, None] = "000013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interview",
        sa.Column(
            "state", sa.String(length=32), nullable=False, server_default="initialized"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interview", "state")
    # ### end Alembic commands ###
