"""add_new_vacancy_fields

Revision ID: 000008
Revises: 000007
Create Date: 2024-09-07 03:30:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "000008"
down_revision: Union[str, None] = "000007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vacancy", sa.Column("company", sa.String(length=255), nullable=True))
    op.add_column(
        "vacancy", sa.Column("location", sa.String(length=255), nullable=True)
    )
    op.add_column("vacancy", sa.Column("salary_min", sa.Integer(), nullable=True))
    op.add_column("vacancy", sa.Column("salary_max", sa.Integer(), nullable=True))
    op.add_column(
        "vacancy", sa.Column("employment_type", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "vacancy", sa.Column("experience_level", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "vacancy",
        sa.Column("remote_work", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column("vacancy", sa.Column("requirements", sa.Text(), nullable=True))
    op.add_column("vacancy", sa.Column("benefits", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancy", "benefits")
    op.drop_column("vacancy", "requirements")
    op.drop_column("vacancy", "remote_work")
    op.drop_column("vacancy", "experience_level")
    op.drop_column("vacancy", "employment_type")
    op.drop_column("vacancy", "salary_max")
    op.drop_column("vacancy", "salary_min")
    op.drop_column("vacancy", "location")
    op.drop_column("vacancy", "company")
    # ### end Alembic commands ###
