"""add_skills_to_candidates

Revision ID: 3a7bf0979312
Revises: 000008
Create Date: 2025-09-07 04:47:51.700629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a7bf0979312'
down_revision: Union[str, None] = '000008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('skills', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'skills')
    # ### end Alembic commands ###


