name: CI Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up backend environment
      working-directory: ./backend
      run: |
        uv sync --dev

    - name: Run Black (code formatting check)
      working-directory: ./backend
      run: |
        uv run black --check --diff .

    - name: Run Ruff (linting)
      working-directory: ./backend
      run: |
        uv run ruff check .

    - name: Run tests with coverage
      working-directory: ./backend
      run: |
        uv run pytest --cov=app --cov-report=xml --cov-report=html

    - name: Upload coverage reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          backend/coverage.xml
          backend/htmlcov/
        retention-days: 7
