name: CI Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Install dependencies
      working-directory: ./frontend
      run: pnpm install --frozen-lockfile

    - name: Run Biome format check
      working-directory: ./frontend
      run: pnpm run format

    - name: Run Biome lint check
      working-directory: ./frontend
      run: pnpm run lint

    - name: Run type checks
      working-directory: ./frontend
      run: pnpm run tsc

    # No tests yet =)
    # - name: Run tests
    #   working-directory: ./frontend
    #   run: pnpm run test

    - name: Build application
      working-directory: ./frontend
      run: pnpm run build
